### PR TITLE
Removes semi colon.

### PR DESCRIPTION
**Pull request by acgandhi**
By suggestion of Nhi.
:)

### CODE REVIEW

**Review by jasonjewik — CHANGES_REQUESTED** [review]
The thing is though, Jason _Kyle Jewik_ just sounds too formal. I want my website to sound more casual.

**Comment by acgandhi** [comment]
How about just Kyle then?

**Comment by jasonjewik** [comment]
But that would cause cognitive dissonance for people. Visitors to my website would see that the URL is [jasonjewik.com](jasonjewik.com), but then the introduction says "Jason Kyle". It would cause great confusion and I'd rather spare the trouble.

**Comment by jasonjewik** [comment]
Request denied.

**Pull request closed without merging**
